# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{qips-rmgr-web}
  s.version = "0.5.6"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["David Austin", "Andrew Brader"]
  s.date = %q{2010-08-19}
  s.description = %q{Works with qips node to manage aws instances based on demand.}
  s.email = %q{daustin@mail.med.upenn.edu}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "app/controllers/application_controller.rb",
     "app/controllers/farms_controller.rb",
     "app/controllers/instances_controller.rb",
     "app/controllers/roles_controller.rb",
     "app/helpers/application_helper.rb",
     "app/helpers/farms_helper.rb",
     "app/helpers/instances_helper.rb",
     "app/helpers/roles_helper.rb",
     "app/models/event_log.rb",
     "app/models/farm.rb",
     "app/models/instance.rb",
     "app/models/role.rb",
     "app/views/farms/_form.html.erb",
     "app/views/farms/edit.html.erb",
     "app/views/farms/index.html.erb",
     "app/views/farms/new.html.erb",
     "app/views/farms/reconcile.html.erb",
     "app/views/farms/reconcile_all.html.erb",
     "app/views/farms/show.html.erb",
     "app/views/instances/index.html.erb",
     "app/views/instances/set_status.html.erb",
     "app/views/layouts/application.html.erb",
     "app/views/roles/_form.html.erb",
     "app/views/roles/edit.html.erb",
     "app/views/roles/index.html.erb",
     "app/views/roles/new.html.erb",
     "app/views/shared/_heading.html.erb",
     "config/boot.rb",
     "config/cucumber.yml",
     "config/database.yml",
     "config/deb_iptables.erb",
     "config/environment.rb",
     "config/environments/cucumber.rb",
     "config/environments/development.rb",
     "config/environments/production.rb",
     "config/environments/test.rb",
     "config/initializers/backtrace_silencers.rb",
     "config/initializers/inflections.rb",
     "config/initializers/mime_types.rb",
     "config/initializers/new_rails_defaults.rb",
     "config/initializers/session_store.rb",
     "config/locales/en.yml",
     "config/nodes.erb",
     "config/routes.rb",
     "config/rpm_iptables.erb",
     "config/schedule.rb",
     "config/user_data.erb",
     "db/migrate/20090929180916_create_farms.rb",
     "db/migrate/20090929181104_create_roles.rb",
     "db/migrate/20090929181338_create_instances.rb",
     "db/migrate/20090929184112_create_users.rb",
     "db/migrate/20090930194449_drop_users.rb",
     "db/migrate/20091001175642_create_recipes.rb",
     "db/migrate/20091002174617_create_recipes_roles.rb",
     "db/migrate/20091002205651_add_key_groups_to_farm.rb",
     "db/migrate/20091006145900_add_launch_time_to_instance.rb",
     "db/migrate/20091007195444_remove_recipes_from_role.rb",
     "db/migrate/20091008182853_add_farm_type_to_farms.rb",
     "db/migrate/20091008183318_add_prov_buffer_launch_buffer_to_roles.rb",
     "db/migrate/20091008183453_add_prov_time_to_instances.rb",
     "db/migrate/20091008184049_remove_enabled_from_farms.rb",
     "db/migrate/20091118204118_remove_prov_time_from_instance.rb",
     "db/migrate/20091118205845_add_state_changed_at_executable_ruby_pid_status_updated_at_to_instance.rb",
     "db/migrate/20091119201845_remove_cpu_top_from_instance.rb",
     "db/migrate/20091119202221_add_ruby_cpu_usage_system_cpu_usage_ruby_mem_usage_system_mem_usage_to_instance.rb",
     "db/migrate/20091119202408_add_top_pid_ruby_pid_status_to_instance.rb",
     "db/migrate/20091120185805_add_cycle_count_to_instance.rb",
     "db/migrate/20091130190402_add_ruby_cycle_count_to_instance.rb",
     "db/migrate/20091204204140_remove_prov_buffer_launch_buffer_from_role.rb",
     "db/migrate/20091204211042_add_kernel_id_to_farm.rb",
     "db/migrate/20091204211325_add_public_dns_name_to_instance.rb",
     "db/migrate/20091207174511_rename_key_groups_in_farm.rb",
     "db/migrate/20100107173252_create_event_logs.rb",
     "db/migrate/20100108202518_add_child_procs_to_instance.rb",
     "db/migrate/20100113170742_add_user_data_to_farm.rb",
     "db/migrate/20100113172653_remove_user_data_from_farm.rb",
     "db/migrate/20100113172711_add_default_user_data_to_farm.rb",
     "db/migrate/20100113174830_add_user_data_to_instance.rb",
     "db/migrate/20100428181844_add_spot_price.rb",
     "db/migrate/20100430152128_change_farms_spot_price.rb",
     "db/migrate/20100521220753_add_recipes_to_role.rb",
     "db/migrate/20100527144817_drop_recipes.rb",
     "db/migrate/20100610193354_create_delayed_jobs.rb",
     "db/migrate/20100706192648_remove_indexes_from_recipe_roles.rb",
     "db/migrate/20100706193330_drop_recipes_roles.rb",
     "db/seeds.rb",
     "doc/README_FOR_APP",
     "features/manage_farm.feature",
     "features/manage_instances.feature",
     "features/manage_roles.feature",
     "features/step_definitions/helper_steps.rb",
     "features/step_definitions/model_steps.rb",
     "features/step_definitions/pickle_steps.rb",
     "features/step_definitions/user_steps.rb",
     "features/step_definitions/web_steps.rb",
     "features/step_definitions/webrat_steps.rb.old",
     "features/support/env.rb",
     "features/support/factories.rb",
     "features/support/paths.rb",
     "features/support/pickle.rb",
     "lib/chef_config_writer.rb",
     "lib/instance_monitor.rb",
     "lib/ip_access_writer.rb",
     "lib/s3_helper.rb",
     "lib/tasks/cucumber.rake",
     "lib/tasks/delayed_jobs.rake",
     "lib/tasks/prep.rake",
     "lib/tasks/rspec.rake",
     "lib/user_data_writer.rb",
     "lib/work_item_helper.rb",
     "pkg/qips-rmgr-web-0.1.0.gem",
     "pkg/qips-rmgr-web-0.2.0.gem",
     "pkg/qips-rmgr-web-0.2.1.gem",
     "pkg/qips-rmgr-web-0.3.0.gem",
     "pkg/qips-rmgr-web-0.3.1.gem",
     "pkg/qips-rmgr-web-0.4.0.gem",
     "pkg/qips-rmgr-web-0.4.1.gem",
     "pkg/qips-rmgr-web-0.4.2.gem",
     "pkg/qips-rmgr-web-0.4.3.gem",
     "public/404.html",
     "public/422.html",
     "public/500.html",
     "public/favicon.ico",
     "public/images/green_atoms.jpg",
     "public/images/qips.png",
     "public/images/rails.png",
     "public/javascripts/application.js",
     "public/javascripts/controls.js",
     "public/javascripts/dragdrop.js",
     "public/javascripts/effects.js",
     "public/javascripts/jquery-1.4.2.min.js",
     "public/javascripts/jquery-ui-1.8.1.custom.min.js",
     "public/javascripts/prototype.js",
     "public/javascripts/ui.multiselect.js",
     "public/robots.txt",
     "public/stylesheets/application.css",
     "public/stylesheets/common.css",
     "public/stylesheets/scaffold.css",
     "public/stylesheets/ui.multiselect.css",
     "qips-rmgr-web.gemspec",
     "script/about",
     "script/autospec",
     "script/console",
     "script/cucumber",
     "script/dbconsole",
     "script/delayed_job",
     "script/destroy",
     "script/generate",
     "script/performance/benchmarker",
     "script/performance/profiler",
     "script/plugin",
     "script/runner",
     "script/server",
     "script/spec",
     "script/spec_server",
     "spec/controllers/farms_controller_spec.rb",
     "spec/controllers/instances_controller_spec.rb",
     "spec/factories.rb",
     "spec/fixtures/farms.yml",
     "spec/fixtures/instances.yml",
     "spec/fixtures/roles.yml",
     "spec/helpers/farms_helper_spec.rb",
     "spec/helpers/instances_helper_spec.rb",
     "spec/integration/farms_spec.rb",
     "spec/integration/instances_spec.rb",
     "spec/models/farm_spec.rb",
     "spec/models/instance_spec.rb",
     "spec/rcov.opts",
     "spec/routing/farms_routing_spec.rb",
     "spec/routing/instances_routing_spec.rb",
     "spec/routing/roles_routing_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/abrader/qips-rmgr-web}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{nowarning}
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Web-based resource manager for QIPS suite.}
  s.test_files = [
    "spec/controllers/farms_controller_spec.rb",
     "spec/controllers/instances_controller_spec.rb",
     "spec/factories.rb",
     "spec/helpers/farms_helper_spec.rb",
     "spec/helpers/instances_helper_spec.rb",
     "spec/integration/farms_spec.rb",
     "spec/integration/instances_spec.rb",
     "spec/models/farm_spec.rb",
     "spec/models/instance_spec.rb",
     "spec/routing/farms_routing_spec.rb",
     "spec/routing/instances_routing_spec.rb",
     "spec/routing/roles_routing_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<erubis>, [">= 2.6.2"])
      s.add_runtime_dependency(%q<json>, [">= 1.2.0"])
      s.add_runtime_dependency(%q<amazon-ec2>, ["= 0.9.3"])
      s.add_runtime_dependency(%q<right_aws>, [">= 1.10.0"])
      s.add_runtime_dependency(%q<octopussy>, [">= 0.2.2"])
      s.add_runtime_dependency(%q<git>, [">= 1.2.5"])
      s.add_runtime_dependency(%q<archive-tar-minitar>, [">= 0.5.2"])
      s.add_runtime_dependency(%q<delayed_job>, ["= 2.0.3"])
      s.add_runtime_dependency(%q<whenever>, [">= 0.5.0"])
      s.add_runtime_dependency(%q<ohai>, [">= 0.5.6"])
      s.add_development_dependency(%q<rspec-rails>, [">= 1.3.2"])
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_development_dependency(%q<cucumber>, [">= 0.4.3"])
      s.add_development_dependency(%q<pickle>, [">= 0.1.21"])
      s.add_development_dependency(%q<cucumber-rails>, [">= 0.3.0"])
      s.add_development_dependency(%q<database_cleaner>, [">= 0.5.0"])
      s.add_development_dependency(%q<webrat>, [">= 0.7.0"])
      s.add_development_dependency(%q<capybara>, ["= 0.3.8"])
      s.add_development_dependency(%q<thoughtbot-factory_girl>, [">= 1.2.1"])
    else
      s.add_dependency(%q<erubis>, [">= 2.6.2"])
      s.add_dependency(%q<json>, [">= 1.2.0"])
      s.add_dependency(%q<amazon-ec2>, ["= 0.9.3"])
      s.add_dependency(%q<right_aws>, [">= 1.10.0"])
      s.add_dependency(%q<octopussy>, [">= 0.2.2"])
      s.add_dependency(%q<git>, [">= 1.2.5"])
      s.add_dependency(%q<archive-tar-minitar>, [">= 0.5.2"])
      s.add_dependency(%q<delayed_job>, ["= 2.0.3"])
      s.add_dependency(%q<whenever>, [">= 0.5.0"])
      s.add_dependency(%q<ohai>, [">= 0.5.6"])
      s.add_dependency(%q<rspec-rails>, [">= 1.3.2"])
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_dependency(%q<cucumber>, [">= 0.4.3"])
      s.add_dependency(%q<pickle>, [">= 0.1.21"])
      s.add_dependency(%q<cucumber-rails>, [">= 0.3.0"])
      s.add_dependency(%q<database_cleaner>, [">= 0.5.0"])
      s.add_dependency(%q<webrat>, [">= 0.7.0"])
      s.add_dependency(%q<capybara>, ["= 0.3.8"])
      s.add_dependency(%q<thoughtbot-factory_girl>, [">= 1.2.1"])
    end
  else
    s.add_dependency(%q<erubis>, [">= 2.6.2"])
    s.add_dependency(%q<json>, [">= 1.2.0"])
    s.add_dependency(%q<amazon-ec2>, ["= 0.9.3"])
    s.add_dependency(%q<right_aws>, [">= 1.10.0"])
    s.add_dependency(%q<octopussy>, [">= 0.2.2"])
    s.add_dependency(%q<git>, [">= 1.2.5"])
    s.add_dependency(%q<archive-tar-minitar>, [">= 0.5.2"])
    s.add_dependency(%q<delayed_job>, ["= 2.0.3"])
    s.add_dependency(%q<whenever>, [">= 0.5.0"])
    s.add_dependency(%q<ohai>, [">= 0.5.6"])
    s.add_dependency(%q<rspec-rails>, [">= 1.3.2"])
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
    s.add_dependency(%q<cucumber>, [">= 0.4.3"])
    s.add_dependency(%q<pickle>, [">= 0.1.21"])
    s.add_dependency(%q<cucumber-rails>, [">= 0.3.0"])
    s.add_dependency(%q<database_cleaner>, [">= 0.5.0"])
    s.add_dependency(%q<webrat>, [">= 0.7.0"])
    s.add_dependency(%q<capybara>, ["= 0.3.8"])
    s.add_dependency(%q<thoughtbot-factory_girl>, [">= 1.2.1"])
  end
end

